steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - function_proyectofinal_gcp
      - --region=europe-west1
      - --runtime
      - python39
      - --trigger-bucket
      - gs://bucket_formulariojson
      - --source=./app
      - --allow-unauthenticated