steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - function_proyectofinal_gcp
      - --region=europe-west1
      - --runtime
      - python39
      - --trigger-bucket
      - gs://bucket_formulariojson
      - --source=./cloudfunction
      - --allow-unauthenticated

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build -t $$USERNAME/app-users-gcp:$COMMIT_SHA .']
    secretEnv: ['USERNAME']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker push $$USERNAME/app-users-gcp:$COMMIT_SHA']
    secretEnv: ['USERNAME']
    
availableSecrets:
  secretManager:
  - versionName: projects/gcp-final-project-405308/secrets/docker-token/versions/DOCKER_PASSWORD_SECRET_VERSION
    env: 'PASSWORD'
  - versionName: projects/gcp-final-project-405308/secrets/docker-username/versions/DOCKER_USERNAME_SECRET_VERSION
    env: 'USERNAME'

  # Deploy to Cloud Run using the image from Docker Hub
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app-users-gcp'
      - --region=europe-west1
      - '--image=ocanha/app-users-gcp:$COMMIT_SHA'  # Use your Docker Hub image
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
